### ISSUE TITLE
App freezes to death

### ISSUE THREAD

**Issue by weleo** [martinlexow/superlayer-support#28]
```
Superlayer 1.0.7
MacBook Pro M1 Max 64 GB
Ventura 13.0.1 (22A400)
```

_I've just purchased and installed Superlayer._ Although CPU and Memory are below 20% load, the app has a prolonged response time for almost any action. Opening settings via the menu bar icon takes a couple of seconds. Removing scenes is impossible; the app freezes and the process must be killed.

I've rebooted once, but the problems persist. I haven't looked more into it since this is a paid product. I can send logs upon request.

**Comment by martinlexow** [comment]
Hi @weleo — I apologise for the circumstances. This behaviour is definitely not expected.

Providing a log file would increase my chances to find the cause. Would you be able to send me one?

Also, since you’re not able to use app, I would like to suggest a refund.

Please get in touch → martin (at) ixeau (dot) com

**Comment by weleo** [comment]
Hi @martinlexow — I am now on **Ventura 13.1**, but the problem _persists_. Where do you save the log files? I was looking in `/Users/me/Library/Application Support`. Here's a quick [video of my UX](https://snaps.leo.ws/9WhIM4).
